Basic Input Handling
JuLuSiLi/jobsjoggt pull request #8
Opened 2021-03-16 22:22 UTC by l-zeuch

#### Summary
Add basic input handling using the `crossterm` crate.

#### Explanation
Added a basic input handler function as a proof-of concept. 
The crate used for this is called [`crossterm`](https://crates.io/crates/crossterm), quite a handy crate especially used for cross-platform to Linux, Windows, and OSX.
Further, we introduce a new file, [`mod.rs`](https://github.com/JuLuSiLi/jobsjoggt/commit/b09fc69fa8e5bc3d2e58a3f7fb7256d054cea3b7#diff-59d15b4bd7b44d1f15c56c5da9cc73b65e64829a6c4aef3b01459be849b76c9e), which allows for exposure to our `main.rs` file for later usage.

As a conclusion I also added a small description of the function inside [`input_handler.rs`](https://github.com/JuLuSiLi/jobsjoggt/commit/81a174b5037f5617eb4d6bedb80d631f275c748a#diff-920be6da0b8d35f2d5663b31a25819fed738037deb5aa52225bd6dcfdaac0660) which further points out the proof of concept and reminds us to write a unit test along with a "working" refactor.

---
**Status**
*Apart from the GitHub action ran automatically on your PR, please confirm the following:*

- [x] code changes have been tested using appropiate testing methods, or there are no code changes.

2021-03-17 07:26 UTC, simjus approved these changes
Looks good. Is it right, that the match expression in input_handler handles only 4 possible Events?

2021-03-17 08:52 UTC, l-zeuch commented
For now, yes.
It is easily expandable by appending
```rs
Event::Key(KeyEvent {
    code: KeyCode::Char('x'),
    modifiers:_no_modifiers,
}) => // Handle the input here
```
Where `x` is the respective key.

2021-03-17 09:07 UTC, Goldscar1 requested changes
No default case, edge cases are not covered

2021-03-17 09:10 UTC, l-zeuch commented
> No default case, edge cases are not covered

Which changes would you suggest, then?
As far as I know, crossterm's `KeyEvent` only triggers when a key is pressed - which edge cases are you talking about?
And what kind of default case would then be needed?

2021-03-17 09:15 UTC, l-zeuch commented
I need to refactor it again, I just took a look at the crossterm documentation.
They way I wanted to implement it will not work.
I'll work something out.

2021-05-30 11:40 UTC, l-zeuch commented
Ay we compiling now bois, green as a christmas tree!
Should be ready now - still all very basic and we surely got to find a concurrent way of handling inputs.

2021-05-30 11:40 UTC, l-zeuch commented
Ay we compiling now bois, green as a christmas tree!
Should be ready now - still all very basic and we surely got to find a concurrent way of handling inputs.

2021-06-02 14:27 UTC, merged